### ISSUE TITLE
Add support for source files install and upgarde

### ISSUE THREAD

**Issue by jttrail0** [confluentinc/cp-ansible#301]
Is it possible to build in an installer for the source files?  This would then support a wider set of distributions or things like RHEL\Centos 8 rpm support which does not yet exist.

 - OS: Any Linux
 - CP-Ansible Branch: [5.5.0-post]
 - Ansible Version [e.g. ansible 2.9.6]

**Comment by domenicbove** [comment]
Can you elaborate more of what you are looking for?
The install should work on centos8 and rhel

Right now it installs with rpms and runs components as linux services. Are you asking for the zip based installer: https://docs.confluent.io/current/installation/installing_cp/zip-tar.html#prod-kafka-cli-install

**Comment by jttrail0** [comment]
Sorry I should have been more specific.  I have not seen a RHEL/Centos 8
repository or the equivalent rpms for download on confluent docs yet.

It would be nice to be able to use this role for the tar/zip files that are
available for download that could be used across a number distros outside
of select deb and rpm based distros.

**Comment by JumaX** [comment]
@jttrail0 We currently do not support RHEL 8 or CentOS 8 at this time.  This will be coming in the future.  Supported OS release can be found here: 

https://docs.confluent.io/current/installation/system-requirements.html#software

We also do not support building from source if that is what you are referring to with regards to "source files".  In order to do this, you would need to go to the Open Source repo for Kafka and build from there: https://github.com/apache/kafka

The README.MD outlines how to do this. 

Thanks for your question.
