### ISSUE TITLE
Run RBAC actions against actually "running" MDS server

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#344]
All the RBAC-uri actions always run against `groups[kafka_broker][0]` meaning they will always only try to target one specific broker.
To ensure one broker down won't hurt the deployment one could do the following:

1. Do a healtcheck against all MDS-API of all brokers
2. Create a temporary hostgroup containg those brokers (https://docs.ansible.com/ansible/latest/modules/group_by_module.html)
3. Run the RBAC statements with `delegate_to` against this hostgroup using `run_once`

In that way one offline broker won't stop the rest of the deployment.

Being all that said -  I am not sure if one would prefer a hard error if `broker0` is down over a `HA` playbook. :thinking:

**Comment by JumaX** [comment]
@Fobhep The context around this is these playbooks are for greenfield installs only.  If broker 0 fails to start, the playbook will error  on the health check before it gets to setting up the next component with RBAC.  The thinking being, you need to make sure you have your brokers configured right before you move on to the next component.  So the order of operations will generally prevent this scenario.

The RBAC commands are also not generally run again after initial deployment, unless you specifically run the component install again, say using a tag for the component with RBAC enabled. Even then, the user will already exist with the appropriate permissions in the MDS, so if the statement failed, it actually won't stop the component from authorizing.  You probably also still want to investigate why broker 0 is down, and the error would tell you that.

The one gap I see, is if you only setup the brokers in your first run, and they pass all health checks, but then setup say schema registry in a second run and in between broker 0 has failed.  Then, you will get an error during Schema Registry setup as the call to broker 0 will fail, which should point you towards figuring out why broker0 is failing in a new deployment.

You probably don't want to push forward with deployment without investigating why you have brokers failing.  

If we started building the tool out for administration, then we would need to rethink this approach, as you are right, its possible you could have a production cluster with broker0 offline, say for maintenance and want to re-run the setup of a component.  However, I would argue that you most likely would not want to run the service user setup again, as the permissions for the service users don't really need to be updated, they are relatively static between release.

I also think there would be a lot of other edge cases/considerations to review for using these as an admin tool.

Let me know if you think I am missing anything.

**Comment by Fobhep** [comment]
@JumaX sorry for the late reply and thanks for your detailed explanation.

I agree to you regarding my original issue. This is most likely not within the very scope. I also understand the limitations and edge cases for using the playbooks as an admin tool.
However this brings me to a much more generic question.
I will write it here, but please feel free to close this issue and we can discuss this maybe elsewhere :)

The docs state clearly:
`Ansible Playbooks for Confluent Platform is for first-time installs only. It should not be used to update configuration in place`

I wonder currently about scenarios that are somewhere in between greenfield and day2day administrative but do actually change config.

eg:

-> Upgrading a cluster from kerberos only to RBAC
-> Updating the connectors config in a cluster
(Could you actually imagine having a extra playbook in this repo that utilizes the kafka_connectors module you are shipping as well)
-> Adding a new disk to a kafka broker
-> Changing global settings (like min.insync.replicas)

Would you use the roles/playbook for things like that?
I think the "Ansible" way would actually be to be able to change a config setting in the very same playbook I use for an installation in the first place.

**Comment by JumaX** [comment]
@Fobhep Agreed there are edge cases still.  However, I still think that even if it's updating the configs during an installation, you should be questioning why broker 0 is down/unavailable.  Going live without understanding why a key piece of a new platform is down is a bad idea.

If you are adding a new disk to a kafka broker and want to update the configs, then you will want to wait until that broker is online before doing so.  Otherwise you will end up with mistmatched configs in your cluster.  So I don't think that is a relevant use case.

Regarding updating connector configs, I think this still falls under the first case I outlined above.  If your broker is offline in a new env, you should understand why that is before proceeding.

Again, I think if this was an existing environment and we supported day 2 operations, the scope would completely change here and we would need to do things like I previously mentioned whereby we limit when the user creation happens for RBAC.

So you are aware, we have had a lot of request for turning this tool into a day2 admin tool, its actively being discussed internally.

**Comment by Fobhep** [comment]
@JumaX thanks for your detailed reply - really appreciate it :)!
I agree completely all those tasks I listed should alwys only run when you have all brokers up and running!

Regarding the list of operations I wrote:
I think I didn't make it clear enough that I'm more interested in principle (regardless of this specific issue) in what operations and configuration changes would be in scope of the playbooks. And where the docs' statement `It should not be used to update configuration in place`
starts to apply.

**Comment by JumaX** [comment]
@Fobhep I would say the general answer is, once you can't afford downtime.  For example, it's very normal to have to reconfigure things a few times when first installing.  Perhaps you don't have all the environment details right away etc.  However, its also probably not a concern if you restart services etc, because it's still being installed/not in production.  I am sure there are edge cases where that is not the case, but I am speaking in general terms here.

**Comment by Fobhep** [comment]
@JumaX ok - that makes actually a lot of sense.
thanks! :) please feel free to close the issue
