### ISSUE TITLE
Splitting of Host file (improvement)

### ISSUE THREAD

**Issue by vision2050** [confluentinc/cp-ansible#387]
This is not an issue, but an improvement suggestion
At present, host file i.e. host.yml contains a lot of configuration information which makes it lengthy and difficult to manage. Host file should ideally just have host details. Rest of the configuration can be split and moved to group_vars or host_vars. something like security_config.yml, properties_config.yml etc.
We have split these locally.

**Comment by JumaX** [comment]
Hello @vision2050,

Thanks for reaching out with your suggestion.  When we started CP-Ansible, our aim was to make it as easy as possible for someone new to Ansible to get up and running quickly, thus why we added the variables and documentation to the single hosts file.  The project has grown over the past year or so, so I can definitely see how this file has become unwieldy to some users, over time.

Can you provide more details on how you have split this out?  Essentially, we would like the community tell us how they want to work with the project, in order to meet the largest audience's needs from a usability perspective.  A break down of what files and what vars you have moved to those files would be super helpful for us to better understand the desired end statate here.

**Comment by domenicbove** [comment]
@vision2050 There is no requirement that you put all vars in your inventory. Doing group_vars is totally acceptable. In fact the official docs (ie docs.confluent.io) that are coming with our next release will have this: 

> You can also make use of group_vars and host_vars directories located next to you inventory file to pass variables. See Ansible Directory Layout.

The hosts_example.yml is def getting bloated. I've added a self documenting variable feature to our next release as well so instead of looking at the hosts_example.yml file you can look at a VARIABLES.md file. Heres a preview: https://github.com/confluentinc/cp-ansible/blob/6.0.x/VARIABLES.md

@JumaX he is referring to this: https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout

**Comment by JumaX** [comment]
@domenicbove I am aware of  https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout

But I would like user feedback to help understand how we can improve.  It maybe the case that there isn't much here, however I am interested in how they have broken out there variable files.  What the structure is etc.

**Comment by vision2050** [comment]
Hi,I have split into multiple files in group_vars. Fos us, most of the config is around security as we are using kerberos and RBACall - config-general.yml, config-security.ymlkafka_broker - config-security.ymlzookeeper - config-security.yml
Regards,Raj
    On Thursday, 27 August 2020, 09:46:44 BST, Justin Manchester <notifications@github.com> wrote:  
 
 


@domenicbove I am aware of https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout

But I would like user feedback to help understand how we can improve. It maybe the case that there isn't much here, however I am interested in how they have broken out there variable files. What the structure is etc.

**Comment by domenicbove** [comment]
@vision2050 What you've done makes sense. The question is, what can we do w this repo though? I don't think we have it written that using group_vars is wrong or unsupported.

**Comment by Fobhep** [comment]
I think a very important thing would be to mention that we are using here merge strategy for hashes, which is NOT default and thus has a potential of confusing people who know Ansible and are new to this repository (at least I fell over that initially ;) )

**Comment by domenicbove** [comment]
I agree hash merging is very important/ confusing. In the docs playbook run example has the current directory being the root of cp-ansible. And this gains you access to our ansible.cfg (with hash merging)
https://docs.confluent.io/current/installation/cp-ansible/ansible-install.html

But I suppose the reason why is not directly called out. Do you think we should add a note @Fobhep ?

Also, this has come up so many times that in the next release we will have an assertion with error message around this: https://github.com/confluentinc/cp-ansible/blob/6.0.x/roles/confluent.common/tasks/main.yml#L2

**Comment by Fobhep** [comment]
@domenicbove I personally would like it to be mentioned at least. Given the fact, that also Ansible is quite picky which ansible.cfg to use based on from where you call your playbook.

I have seen people keeping their inventories and other "personalized stuff" outside of the cp-ansible folder, to ensure a git update won't interfere here.
If you call the playbook then not from inside cp-ansible

`ansible-playbook cp-ansible/all.yaml -i hosts-file.yml`

it won't respect the ansible.cfg and fail. But the resulting error message is not exactly helpful for everyone :)

+1 for the assert!

**Comment by domenicbove** [comment]
@Fobhep We added a not about hash merging to our docs: https://docs.confluent.io/current/installation/cp-ansible/ansible-install.html

@vision2050 We have it documented that host_vars and group_vars are an ok approach here: https://docs.confluent.io/current/installation/cp-ansible/ansible-configure.html#set-ansible-host-variables

How do those look? I think this can be closed
