### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by rudolfvavra** [confluentinc/cp-ansible#66]
Hi
Please could you add support for kerberos? Why "Setting up a Kerberos KDC or integration with Active Directory " is out of Scope? 

SASL_PLAINTEXT is not enough. Via ansible variables we can just give our own keytab, principal, path and similar. This should be better for automation, testing and debugging across all the nodes in the cluster
Source:
https://docs.confluent.io/current/tutorials/cp-ansible/docs/index.html

Thank you very much, cheers
-Rudolf

**Comment by cotedm** [comment]
@rudolfvavra this is out of scope for this playbook because we do not set up a KDC and so this would not be verifiable within the scope of the playbook. Please note that these playbooks are intended as a guideline and not to cover all cases. However, you can easily extend the SASL_SSL example to use the GSSAPI ``sasl.mechanism`` and provide a JAAS configuration that is suitable for kerberos. If you have your own keytabs and can access the KDC from all machines then you can use configuration overrides to accomplish your goal.

**Comment by rudolfvavra** [comment]
Thank you very much, please are there any deployment scripts with kerberos or ldap? 

Maybe for your testing lab I can imagine that default KDC configuration should be verifiable within the scope of the playbook  - Or how did you create any documentation about GSSAPI (https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_gssapi.html ) on the first place? In the lab there must be some GSSAPI lab configuration deployment for the cluster across multiple nodes. Or how testing of GSSAPI configuration or this role is done? This ansible role can be refactor, more variables for principal, all jaas parameters ( keytab, debug, useTicketCache, useKeyTab) ... - could be listed in defaults/main.yml. In this way we can build the playbook for different KDC settings. Also SSL path to keystore and truststore is defined on multiple places and it's hardcoded - this should be also rewritten. In ideal case i could just change my hosts.cfg, my credentials and some paths in my playbook ...

**Comment by JumaX** [comment]
Closing this issue out as it appears to have been answered.
