### ISSUE TITLE
Default to Java 11 instead of 8

### ISSUE THREAD

**Issue by chuck-confluent** [confluentinc/cp-ansible#662]
**For Confluent Enterprise Support customers, we would strongly advise you to open a Support ticket which will be addressed within your Support contract SLA at ```https://support.confluent.io```**

**Describe the issue**
The default java version is 8, but I think there are significant performance benefits to using java 11, especially with ssl/tls enabled.

**Comment by JumaX** [comment]
@chuck-confluent we have had this on our internal roadmap for a while, however there are a lot of caveats with running anything other then Java 8 currently. For example, the HDFS connector doesn't work with newer Java versions due to limits in some of the Hadoop libs.

Additionally the project is designed to keep with our current recommended best practices, and as per the documentation, we still recommend Java 8: https://docs.confluent.io/platform/current/installation/versions-interoperability.html

We will actually need the platform itself to start recommending Java 12 as the default before we can move down this path.

**Comment by erikgb** [comment]
> Additionally the project is designed to keep with our current recommended best practices, and as per the documentation, we still recommend Java 8: https://docs.confluent.io/platform/current/installation/versions-interoperability.html

@JumaX I do not read the documentation as Java 8 is still recommended. Could you elaborate, please? All the Confluent images are now based on UBI 8 with Azul Zulu Java 11. So I would support changing the **default** JDK to Java 11 in cp-ansible, as both Java 8 and Java 11 is supported in general. When using the HDFS connector, you would have to take care. Are there any other components not supporting Java 11?

**Comment by JumaX** [comment]
@erikgb You are completely right!  I mis-read that matrix! The formatting is not the easiest to follow.  

@chuck-confluent I take my previous response back, we should be able to default to Java 11 then.  Apologies, misread the matrix.

**Comment by domenicbove** [comment]
Java 11 will be the default in our next major release!
