### ISSUE TITLE
Schema Registry Upgrade fails from 5.5.4 to 6.1.1

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#678]
**For Confluent Enterprise Support customers, we would strongly advise you to open a Support ticket which will be addressed within your Support contract SLA at ```https://support.confluent.io```**

**Describe the issue**
When upgrading from 5.5.4 to 6.1.1 an upgrade of schema-registry fails with the error:
```
"Status code was 404 and not [200]: HTTP Error 404: Not Found", "redirected": false, "status": 404, "url": "https://group0-broker3.hcloud-kafka-lab.test:8090/kafka/v3/clusters"}
```

Checking the broker.settings file one can find
```
kafka.rest.enable=false

```

which might be connected to that.

**To Reproduce**
Run 
```
ansible-playbook -i inventor.yml upgrade_schema_registry.yml
```

**Expected behaviour**
Either the docs should clearly state to enable the rest interface manually - or the upgrade playbook should take care of that.
Setting manually `kafka_broker_rest_proxy_enabled: true` fixed the issue

**Comment by domenicbove** [comment]
Ah ya good point, our upgrade docs should call this out. At one point I had a playbook that turned the kafka admin api on after the upgrade: https://github.com/confluentinc/cp-ansible/blob/6.0.0-post/upgrade_kafka_broker_rest_configuration.yml

So if you upgraded to 6.0.1 then you could have enabled it then. But since you are on 6.1.1, you can use the reconfiguration feature to enable it. Our docs should say:

To enable Admin Api if you have an rbac enabled cluster starting at 5.5.a, set these variables:
```
deployment_strategy: rolling
kafka_broker_custom_properties:
  inter.broker.protocol.version: 2.7
  log.message.format.version: 2.5
```
(make sure those props match whats in your server.properties)

And run
```
ansible-playbook -i hosts.yml all.yml --skip-tags package --tags kafka_broker
```
